language: java
jdk:
  - oraclejdk7

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"


# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "cxy4zYXm2v6xK+M/jm1UX88rKUJlsG+RqnmdJLxsNwhRtidQtKJgrQi5nSNGpSoV0j1Z5BB5oMXB0ztex2S65ja07e3q7zeMKmNleU39iYpPg3RAGzujElTLjT+CrGnMx54MtvYgUWfBeKmnvZoBNAqDi28faBCRH156Ej4gwFQ="
    - secure: "HZFuB9haMWMeDrVzWCG8/4xEBn/MJ2MF0RGWKyv8hOwI2tEoLKI9RNKff5yTMMhVm1+HWFoEVSZeX9s6yO/854ddjbAdwukm+uWAiKvyXgjUbkq0V7YtfntbJZsYurISTUfsY2zX1HpiuyANr4UnEqPE88HBgt5VCodtwm2ZQPI="
